name = "projectneura-join"
compatibility_date = "2026-05-03"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "projectneura-join"
database_id = "f946d1f0-82ed-4459-9029-f434072cf6b7"
migrations_dir = "migrations"
